name: shoulders
description: On The Shoulders of Giants.
publish_to: 'none'
version: 0.1.0

environment:
   sdk: '>=3.0.6 <4.0.0'
dependencies:
   flutter:
      sdk: flutter

dev_dependencies:
   flutter_test:
      sdk: flutter
   flutter_lints: ^2.0.0
   flutter_launcher_icons: ^0.13.1

flutter:
   uses-material-design: true
   assets:
      - assets/images/

flutter_launcher_icons:
   image_path: 'assets/images/logo.jpg'
   ios: true
   android: true
